StainedGlass.Web/Controllers/Admin/ChurchController.cs
using Microsoft.AspNetCore.Mvc;
using StainedGlass.Persistence.Templates;
using StainedGlass.Transfer;
using StainedGlass.Transfer.DTOs;

namespace StainedGlass.Web.Controllers.Admin;

[Route("admin/[controller]")]
public class ChurchController : AdminController
{
    private InputBoundary _useCaseInteractor;
    public ChurchController(InputBoundary useCaseInteractor)
    {
        _useCaseInteractor = useCaseInteractor;
        ((UseCaseInteractor)_useCaseInteractor).SetPersistenceTemplate(new DatabasePersistenceTemplate());
    }

    [HttpGet("church")]
    public async override Task<IActionResult> New()
    {
        return View("Admin/Church/NewChurch");
    }
    
    [HttpGet("churches")]
    public override async Task<IActionResult> All()
    {
        ViewBag.Churches = await _useCaseInteractor.GetAllDTOs<ChurchDTO>();
        return View("Admin/Church/Churches");
    }
    
    [HttpGet("{slug}")]
    public override async Task<IActionResult> One(string slug)
    {
        ViewBag.Church = await _useCaseInteractor.GetDTOBySlug<ChurchDTO>(slug);
        if (ViewBag.Church.Image != null && ViewBag.Church.Image.Length > 0) 
        { 
            ViewBag.ChurchImage = await ((ImageDisplayingInterface)this).IFormFileToBase64(ViewBag.Church.Image);
        }
        return View("Admin/Church/Church");
    }
    
    [HttpGet("{slug}/edit")]
    public override async Task<IActionResult> Edit(string slug)
    {
        ViewBag.Church = await _useCaseInteractor.GetDTOBySlug<ChurchDTO>(slug);
        if (ViewBag.Church.Image != null && ViewBag.Church.Image.Length > 0) 
        { 
            ViewBag.ChurchImage = await ((ImageDisplayingInterface)this).IFormFileToBase64(ViewBag.Church.Image);
        }
        return View("Admin/Church/EditChurch");
    }
    
    [HttpDelete("{slug}")]
    public override async Task<IActionResult> Delete(string slug)
    {
        await _useCaseInteractor.RemoveEntity<ChurchDTO>(slug);
        return Ok();
    }
}

StainedGlass.Web/Controllers/ChurchController.cs
using Microsoft.AspNetCore.Mvc;
using StainedGlass.Persistence.Templates;
using StainedGlass.Transfer;
using StainedGlass.Transfer.DTOs;

namespace StainedGlass.Web.Controllers;

[Route("[controller]")]
public class ChurchController : Controller
{
    private InputBoundary _useCaseInteractor;
    
    private const long maxFileSize = 7 * 1024 * 1024; // 7MB in bytes
    private static readonly string[] allowedExtensions = new[] { ".jpg", ".jpeg"};

    public ChurchController(InputBoundary useCaseInteractor)
    {
        _useCaseInteractor = useCaseInteractor;
        ((UseCaseInteractor)_useCaseInteractor).SetPersistenceTemplate(new DatabasePersistenceTemplate());
    }

    [HttpGet]
    public async Task<IActionResult> Get()
    {
        var churches = _useCaseInteractor.GetAllDTOs<ChurchDTO>();
        return Ok(churches);
    }

    [HttpGet("{slug}")]
    public async Task<IActionResult> Get(string slug)
    {
        var church = _useCaseInteractor.GetDTOBySlug<ChurchDTO>(slug);
        return Ok(church);
    }

    [HttpPost]
    public async Task<IActionResult> Post([FromForm]ChurchDTO churchDto)
    {
        var fileValidationResult = ValidateFile(churchDto.Image);
        if (fileValidationResult != null)
        {
            ModelState.AddModelError("Image", fileValidationResult);
            return View("Admin/Church/NewChurch");
        }

        await _useCaseInteractor.StoreEntity(churchDto);
        return Redirect("Admin/Church/churches");
    }

    [HttpPut("{originalSlug}")]
    public async Task<IActionResult> Put(string originalSlug, ChurchDTO churchDto)
    {
        var fileValidationResult = ValidateFile(churchDto.Image);
        if (fileValidationResult != null)
        {
            ModelState.AddModelError("Image", fileValidationResult);
            return View("Admin/Church/EditChurch");
        }
        
        await _useCaseInteractor.ReplaceEntity(originalSlug, churchDto);
        return Ok();
    }

    private string? ValidateFile(IFormFile image)
    {
        if (image != null && image.Length > 0)
        {
            //check the image length
            if (image.Length > maxFileSize)
            {
                return "The file size exceeds the 7MB limit.";
            }
            
            //check the image extension
            var extension = Path.GetExtension(image.FileName).ToLowerInvariant();
            if (!allowedExtensions.Contains(extension))
            {
                return "Invalid file type.";
            }
        }
        
        return null;
    }
}

StainedGlass.Web/Controllers/Crud/ChurchController.cs
using Microsoft.AspNetCore.Mvc;
using StainedGlass.Persistence.Templates;
using StainedGlass.Transfer;
using StainedGlass.Transfer.DTOs;

namespace StainedGlass.Web.Controllers.Crud;

[Route("[controller]")]
public class ChurchController : CrudController
{
    public ChurchController(InputBoundary useCaseInteractor)
    {
        _useCaseInteractor = useCaseInteractor;
        ((UseCaseInteractor)_useCaseInteractor).SetPersistenceTemplate(new DatabasePersistenceTemplate());
    }

    [HttpGet]
    public override async Task<IActionResult> Get()
    {
        var churches = await _useCaseInteractor.GetAllDTOs<ChurchDTO>();
        return Ok(churches);
    }

    [HttpGet("{slug}")]
    public override async Task<IActionResult> Get(string slug)
    {
        var church = await _useCaseInteractor.GetDTOBySlug<ChurchDTO>(slug);
        return Ok(church);
    }

    [HttpPost]
    public async Task<IActionResult> Post([FromForm]ChurchDTO churchDto)
    {
        var fileValidationResult = ValidateFile((churchDto as ChurchDTO).Image);
        if (fileValidationResult != null)
        {
            ModelState.AddModelError("Image", fileValidationResult);
            return View("Admin/Church/NewChurch");
        }

        await _useCaseInteractor.StoreEntity(churchDto);
        return Redirect("Admin/Church/churches");
    }

    [HttpPut("{originalSlug}")]
    public async Task<IActionResult> Put(string originalSlug, ChurchDTO churchDto)
    {
        var fileValidationResult = ValidateFile((churchDto as ChurchDTO).Image);
        if (fileValidationResult != null)
        {
            ModelState.AddModelError("Image", fileValidationResult);
            return View("Admin/Church/EditChurch");
        }
        
        await _useCaseInteractor.ReplaceEntity(originalSlug, churchDto);
        return Ok();
    }
    
    [HttpDelete("{slug}")]
    public override async Task<IActionResult> Delete(string slug)
    {
        await _useCaseInteractor.RemoveEntity<ChurchDTO>(slug);
        return Ok();
    }
}

StainedGlass.Web/Pages/Shared/Admin/Church/Church.cshtml
@page

@{
    Layout = "_AdminLayout";
}

<h2>Church @ViewBag.Church.Slug</h2>

<dl>
    <dt>Name:</dt>
    <dd>@ViewBag.Church.Name</dd>
    <dt>Description:</dt>
    <dd>@ViewBag.Church.Description</dd>
    <dt>Image:</dt>
    <dd>
        @if (ViewBag.ChurchImage != null)
        {
            <img width="150px" src="data:image/jpeg;base64,@ViewBag.ChurchImage" alt="Church @ViewBag.Church.Name Image" />
        }
    </dd>
</dl>

StainedGlass.Web/Pages/Shared/Admin/Church/Churches.cshtml
@page
@using StainedGlass.Transfer.DTOs

@{
    Layout = "_AdminLayout";
    var items = ViewBag.Churches as List<ChurchDTO>;
    int count = 1;
}
<h2 style="display: inline-block;">Churches</h2> 
<a style="position: relative;
    left: 20px;
    bottom: 3px;" href="/admin/church/church">Add a church</a>
<table class="table table-bordered">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Slug</th>
        <th scope="col">Description</th>
        <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    @if (items.Count > 0)
    {
        @foreach (var item in items)
        {
            <tr>
                <th scope="row">@count</th>
                <td>@item.Name</td>
                <td><a href="/admin/church/@item.Slug">@item.Slug</a></td>
                <td>@item.Description</td>
                <td>
                    <a href="/admin/church/@item.Slug/edit">Edit</a>
                    <form>
                        <button class="delete" data-type="church" data-slug="@item.Slug">Delete</button>
                    </form>
                </td>
            </tr>
            count++;
        }
    }
    else
    {
        <tr>
            <td style="text-align: center;" colspan="4">No Churches</td>
        </tr>
    }
    </tbody>
</table>

StainedGlass.Web/Pages/Shared/Admin/Church/EditChurch.cshtml
@page
@* @model StainedGlass.Transfer.DTOs.ChurchDTO; *@

@{
    Layout = "_AdminLayout";
    var redirectUrl = Url.Action("All", "Church");
}

<h2>Church @ViewBag.Church.Slug</h2>

<form action="" method="post" id="editForm" data-type="church" data-slug="@ViewBag.Church.Slug" data-redirect-url="@redirectUrl" enctype="multipart/form-data">
    <div class="form-group">
        <label for="title">Name</label>
        <input type="text" name="Name" required value="@ViewBag.Church.Name" class="form-control" id="name" placeholder="Name">
    </div>
    <br>
    <div class="form-group">
        <label for="text">Description</label>
        <textarea class="form-control" name="Description" required id="description" rows="6">@ViewBag.Church.Description</textarea>
    </div>
    <div class="form-group">
        <label for="image">Image</label>
        @if (ViewBag.ChurchImage != null)
        {
            <br><img width="150px" src="data:image/jpeg;base64,@ViewBag.ChurchImage" alt="Church @ViewBag.Church.Name Image" /><br/>
        }
        <input type="file" name="Image" accept=".jpg, .jpeg" class="form-control-file" id="image">
        @* <span asp-validation-for="Image" class="text-danger"></span> *@
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

StainedGlass.Web/Pages/Shared/Admin/Church/NewChurch.cshtml
@page
@* @model StainedGlass.Transfer.DTOs.ChurchDTO *@

@{
    Layout = "_AdminLayout";
}
<h2 style="display: inline-block;">Adding a new Church</h2>
<br>
<form action="/church" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="title">Name</label>
        <input type="text" name="Name" required class="form-control" id="name" placeholder="Name">
    </div>
    <div class="form-group">
        <label for="title">Slug</label>
        <input type="text" name="Slug" required class="form-control" id="slug" placeholder="Slug">
    </div>
    <br>
    <div class="form-group">
        <label for="text">Description</label>
        <textarea class="form-control" name="Description" required id="description" rows="6"></textarea>
    </div>
    <br/>
    <div class="form-group">
        <label for="image">Image</label>
        <br/>
        <input type="file" name="Image" required class="form-control-file" accept=".jpg, .jpeg" id="image">
        @* <span asp-validation-for="Image" class="text-danger"></span> *@
    </div>
    <br/>
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>