StainedGlass.Web/Controllers/Admin/SanctuarySideController.cs
using Microsoft.AspNetCore.Mvc;
using StainedGlass.Persistence.Templates;
using StainedGlass.Transfer;
using StainedGlass.Transfer.DTOs;

namespace StainedGlass.Web.Controllers.Admin;

[Route("admin/[controller]")]
public class SanctuarySideController : AdminController
{
    private InputBoundary _useCaseInteractor;
    public SanctuarySideController(InputBoundary useCaseInteractor)
    {
        _useCaseInteractor = useCaseInteractor;
        ((UseCaseInteractor)_useCaseInteractor).SetPersistenceTemplate(new DatabasePersistenceTemplate());
    }
    
    [HttpGet("sanctuaryside")]
    public override async Task<IActionResult> New()
    {
        ViewBag.Churches = await _useCaseInteractor.GetAllDTOs<ChurchDTO>();
        if (ViewBag.Churches != null)
        {
            ViewBag.ChurchesImages = new Dictionary<string, string>();
            foreach (var church in ViewBag.Churches)
            {
                ViewBag.ChurchesImages[church.Slug] = 
                    await ((ImageDisplayingInterface)this).IFormFileToBase64(church.Image);
            }
        }
        return View("Admin/SanctuarySide/NewSanctuarySide");
    }

    [HttpGet("sanctuarysides")]
    public override async Task<IActionResult> All()
    {
        ViewBag.SanctuarySides = await _useCaseInteractor.GetAllDTOs<SanctuarySideDTO>();
        return View("Admin/SanctuarySide/SanctuarySides");
    }

    [HttpGet("{slug}")]
    public override async Task<IActionResult> One(string slug)
    {
        ViewBag.SanctuarySide = await _useCaseInteractor.GetDTOBySlug<SanctuarySideDTO>(slug);
        if (ViewBag.SanctuarySide.Church.Image != null && ViewBag.SanctuarySide.Church.Image.Length > 0)
        {
            ViewBag.ChurchImage = 
                await ((ImageDisplayingInterface)this).IFormFileToBase64(ViewBag.SanctuarySide.Church.Image);
        }
        return View("Admin/SanctuarySide/SanctuarySide");
    }

    [HttpGet("{slug}/edit")]
    public override async Task<IActionResult> Edit(string slug)
    {
        ViewBag.SanctuarySide = await _useCaseInteractor.GetDTOBySlug<SanctuarySideDTO>(slug);
        ViewBag.Churches = await _useCaseInteractor.GetAllDTOs<ChurchDTO>();
        if (ViewBag.Churches != null)
        {
            ViewBag.ChurchesImages = new Dictionary<string, string>();
            foreach (var church in ViewBag.Churches)
            {
                ViewBag.ChurchesImages[church.Slug] = 
                    await ((ImageDisplayingInterface)this).IFormFileToBase64(church.Image);
            }
        }

        return View("Admin/SanctuarySide/EditSanctuarySide"); 
    }

    [HttpDelete("{slug}")]
    public override async Task<IActionResult> Delete(string slug)
    {
        await _useCaseInteractor.RemoveEntity<SanctuarySideDTO>(slug);
        return Ok();
    }
}

StainedGlass.Web/Controllers/Crud/SanctuarySideController.cs
using Microsoft.AspNetCore.Mvc;
using StainedGlass.Persistence.Templates;
using StainedGlass.Transfer;
using StainedGlass.Transfer.DTOs;

namespace StainedGlass.Web.Controllers.Crud;

[Route("[controller]")]
public class SanctuarySideController : CrudController
{
    public SanctuarySideController(InputBoundary useCaseInteractor)
    {
        _useCaseInteractor = useCaseInteractor;
        ((UseCaseInteractor)_useCaseInteractor).SetPersistenceTemplate(new DatabasePersistenceTemplate());
    }

    [HttpGet]
    public override async Task<IActionResult> Get()
    {
        var sides = await _useCaseInteractor.GetAllDTOs<SanctuarySideDTO>();
        return Ok(sides);
    }

    [HttpGet("{slug}")]
    public override async Task<IActionResult> Get(string slug)
    {
        var side = await _useCaseInteractor.GetDTOBySlug<SanctuarySideDTO>(slug);
        return Ok(side);
    }

    [HttpPost]
    public async Task<IActionResult> Post([FromForm] SanctuarySideDTO sanctuarySideDTO)
    {
        await _useCaseInteractor.StoreEntity(sanctuarySideDTO);
        return Redirect("Admin/SanctuarySide/SanctuarySides");
    }

    [HttpPut("{originalSlug}")]
    public async Task<IActionResult> Put(string originalSlug, [FromForm] SanctuarySideDTO sanctuarySideDTO)
    {
        await _useCaseInteractor.ReplaceEntity(originalSlug, sanctuarySideDTO);
        return Ok();
    }

    [HttpDelete("{slug}")]
    public override async Task<IActionResult> Delete(string slug)
    {
        await _useCaseInteractor.RemoveEntity<SanctuarySideDTO>(slug);
        return Ok();
    }
}

StainedGlass.Web/Pages/Shared/Admin/SanctuarySide/EditSanctuarySide.cshtml
@page
@using StainedGlass.Transfer.DTOs

@{
    Layout = "_AdminLayout";
    var churches = ViewBag.Churches as List<ChurchDTO>;    
    var redirectUrl = Url.Action("All", "SanctuarySide");
}

<h2>Sanctuary Side @ViewBag.SanctuarySide.Slug</h2>

<form action="" method="post" id="editForm" data-type="sanctuarySide" data-slug="@ViewBag.SanctuarySide.Slug" data-redirect-url="@redirectUrl" enctype="multipart/form-data">
    <div class="form-group">
        <label for="title">Name</label>
        <input type="text" name="Name" required value="@ViewBag.SanctuarySide.Name" class="form-control" id="name" placeholder="Name">
    </div>
    <div class="form-group">
        <label for="title">Church</label>
        <br/>
        <select class="custom-select" id="parentSlug" data-type="sanctuary side" required name="ChurchSlug">
            
            @foreach (var church in churches)
            {
                @if (church.Slug.Equals(ViewBag.SanctuarySide.ChurchSlug))
                {
                    <option selected value="@church.Slug">@church.Name</option>
                }
                else
                {
                     <option value="@church.Slug">@church.Name</option>   
                }
            }
        </select>
    </div>
    <div class="form-group">
        <label for="title">Position</label>
        <br/>
        <div id="positionContainer" class="position-image-container crosshair">
            <img 
                width="150px" 
                id="parentImage" 
                src="data:image/jpeg;base64,@ViewBag.ChurchesImages[ViewBag.SanctuarySide.Church.Slug]" 
                alt="Church @ViewBag.SanctuarySide.Church.Name Image" />
            <i class="bi bi-asterisk" id="elementPosition" style="position: absolute; @ViewBag.SanctuarySide.Position"></i>
        </div>
        <input type="hidden" name="Position" id="positionInput" value="@ViewBag.SanctuarySide.Position" />
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
<div style="display:none;" id="parentImages">
    @if(ViewBag.ChurchesImages != null)
    {
        @foreach (var kvp in ViewBag.ChurchesImages)
        {
            <p class="@kvp.Key">@kvp.Value</p>
        }
    }
</div>

StainedGlass.Web/Pages/Shared/Admin/SanctuarySide/NewSanctuarySide.cshtml
@page
@using StainedGlass.Transfer.DTOs

@{
    Layout = "_AdminLayout";
    var churches = ViewBag.Churches as List<ChurchDTO>;
}
<h2 style="display: inline-block;">Adding a new Sanctuary Side</h2>
<br>
<form action="/sanctuarySide" method="post" id="addForm" enctype="multipart/form-data">
    <div class="form-group">
        <label for="title">Name</label>
        <input type="text" name="Name" required class="form-control" id="name" placeholder="Name">
    </div>
    <div class="form-group">
        <label for="title">Slug</label>
        <input type="text" name="Slug" required class="form-control" id="slug" placeholder="Slug">
    </div>
    <div class="form-group">
        <label for="title">Church</label>
        <br/>
        <select class="custom-select" id="parentSlug" data-type="sanctuary side" required name="ChurchSlug">
            @if (churches.Count > 0)
            {
                <option selected value="0">Choose...</option>
                @foreach (var church in churches)
                {
                    <option value="@church.Slug">@church.Name</option>
                }
            }
            else
            {
                <div class="alert alert-danger" role="alert">
                    There are no churches available. You need to create one first!
                </div>
            }
        </select>
    </div>
    <div class="form-group">
        <label for="title">Position</label>
        <br/>
        <div id="positionContainer" class="position-image-container crosshair"></div>
        <input type="hidden" name="Position" id="positionInput">
    </div>
    <br/>
    @if (churches.Count == 0)
    {
        <div class="form-group">
            <button type="submit" class="btn btn-primary" disabled>Submit</button>
        </div>
    }
    else
    {
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    }
</form>
<div style="display:none;" id="parentImages">
    @if(ViewBag.ChurchesImages != null)
    {
        @foreach (var kvp in ViewBag.ChurchesImages)
        {
            <p class="@kvp.Key">@kvp.Value</p>
        }
    }
</div>

StainedGlass.Web/Pages/Shared/Admin/SanctuarySide/SanctuarySide.cshtml
@page

@{
    Layout = "_AdminLayout";
}

<h2>Sanctuary Side @ViewBag.SanctuarySide.Slug</h2>

<dl>
    <dt>Name:</dt>
    <dd>@ViewBag.SanctuarySide.Name</dd>
    <dt>Church:</dt>
    <dd>@ViewBag.SanctuarySide.Church.Name</dd>
    <dt>Position:</dt>
    <dd>
        @if (ViewBag.ChurchImage != null)
        {
            <div class="position-image-container">
                <img width="150px" src="data:image/jpeg;base64,@ViewBag.ChurchImage" alt="Church @ViewBag.SanctuarySide.Church.Name Image" />
                <i class="bi bi-asterisk" style="position: absolute; @ViewBag.SanctuarySide.Position"></i>
            </div>
        }
    </dd>
</dl>

StainedGlass.Web/Pages/Shared/Admin/SanctuarySide/SanctuarySides.cshtml
@page
@using StainedGlass.Transfer.DTOs

@{
    Layout = "_AdminLayout";
    var items = ViewBag.SanctuarySides as List<SanctuarySideDTO>;
    int count = 1;
}
<h2 style="display: inline-block;">SanctuarySides</h2> 
<a style="position: relative;
    left: 20px;
    bottom: 3px;" href="/admin/sanctuaryside/sanctuaryside">Add a sanctuary side</a>
<table class="table table-bordered">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Slug</th>
        <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    @if (items.Count > 0)
    {
        @foreach (var item in items)
        {
            <tr>
                <th scope="row">@count</th>
                <td>@item.Name</td>
                <td><a href="/admin/sanctuaryside/@item.Slug">@item.Slug</a></td>
                <td>
                    <a href="/admin/sanctuaryside/@item.Slug/edit">Edit</a>
                    <form>
                        <button class="delete" data-type="SanctuarySide" data-slug="@item.Slug">Delete</button>
                    </form>
                </td>
            </tr>
            count++;
        }
    }
    else
    {
        <tr>
            <td colspan="4" style="text-align: center;">No Sanctuary sides</td>
        </tr>
    }
    </tbody>
</table>